"""add indexes

Revision ID: 19429346301a
Revises: 8f5b451bdcb4
Create Date: 2026-03-03 16:45:31.180287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19429346301a'
down_revision: Union[str, Sequence[str], None] = '8f5b451bdcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_batches_expiry_date'), 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_medicine_id'), 'batches', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_batches_pharmacy_id'), 'batches', ['pharmacy_id'], unique=False)
    op.add_column('invoice_items', sa.Column('batch_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_invoice_items_batch_id'), 'invoice_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_medicine_id'), 'invoice_items', ['medicine_id'], unique=False)
    op.create_foreign_key(None, 'invoice_items', 'batches', ['batch_id'], ['id'])
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_pharmacy_id'), 'invoices', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_index(op.f('ix_medicines_pharmacy_id'), 'medicines', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_purchases_created_at'), 'purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchases_pharmacy_id'), 'purchases', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_pharmacy_id'), 'suppliers', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_pharmacy_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_pharmacy_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_created_at'), table_name='purchases')
    op.drop_index(op.f('ix_medicines_pharmacy_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_invoices_pharmacy_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_items_medicine_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_batch_id'), table_name='invoice_items')
    op.drop_column('invoice_items', 'batch_id')
    op.drop_index(op.f('ix_batches_pharmacy_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_medicine_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_expiry_date'), table_name='batches')
    # ### end Alembic commands ###
