"""initial migration

Revision ID: 8f5b451bdcb4
Revises: 
Create Date: 2026-03-02 18:45:16.916859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5b451bdcb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_constraint(op.f('invoice_items_batch_id_fkey'), 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'total_price')
    op.drop_column('invoice_items', 'batch_id')
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'invoice_number')
    op.add_column('invoice_items', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invoice_items_batch_id_fkey'), 'invoice_items', 'batches', ['batch_id'], ['id'])
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], name=op.f('inventory_medicine_id_fkey')),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('inventory_pharmacy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    # ### end Alembic commands ###
