"""add soft delete columns

Revision ID: af2c546bda46
Revises: 4f5bbe489ec6
Create Date: 2026-03-03 17:01:25.182085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2c546bda46'
down_revision: Union[str, Sequence[str], None] = '4f5bbe489ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_batches_is_active'), 'batches', ['is_active'], unique=False)
    op.alter_column('medicines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_medicines_is_active'), 'medicines', ['is_active'], unique=False)
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_column('suppliers', 'is_active')
    op.drop_index(op.f('ix_medicines_is_active'), table_name='medicines')
    op.alter_column('medicines', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_batches_is_active'), table_name='batches')
    op.drop_column('batches', 'is_active')
    # ### end Alembic commands ###
